### ISSUE TITLE
Create pagination for component that lists content (albums, tracks, playlists, etc) 

### ISSUE THREAD

**Issue by mathkruger** [mathkruger/litefy#11]
it may be a infinite scroll, I think that's sounds cool

**Comment by rushatgabhane** [comment]
Hi, can I pick this issue?

**Comment by JPYamamoto** [comment]
I'd like to work on this if you'll assign it to me :)

**Comment by mathkruger** [comment]
@JPYamamoto Fell free to work on it! Thanks for your help!
