### ISSUE TITLE
Convert application to PWA

### ISSUE THREAD

**Issue by lucasluizss** [mathkruger/litefy#116]
Progressive Web Apps (PWAs) are applications that you build by using web technologies, and that can be installed and can run on all devices, from one codebase.

PWAs provide native-like experiences to your users on supporting devices. They adapt to the capabilities supported by each device and they can also run in web browsers, like websites.

**Comment by mathkruger** [comment]
This app is already a PWA, you can add it to the home screen on android and ios.
