### ISSUE TITLE
Flagsapi call fails for missing flag and the Filipino flag is missing

### ISSUE THREAD

**Issue by Antony-jeban** [mathkruger/litefy#142]
Filipino flag is not displaying properly.

Please refer to the attached gif for reference.
![Litefy_bug_fix](https://github.com/user-attachments/assets/1ad3ada0-c764-427b-b0ff-12f87ee9b03b)

**Comment by rutvikv09** [comment]
This issue is open ??

**Comment by Antony-jeban** [comment]
Yes it is open, But this PR(https://github.com/mathkruger/litefy/pull/143) will resolve this issue.

**Comment by mathkruger** [comment]
Bug fixed
