### ISSUE TITLE
Errorhandling when not premium

### ISSUE THREAD

**Issue by semla** [mathkruger/litefy#15]
I am getting errors because I am not premium.
![Screenshot from 2021-02-04 09-23-48](https://user-images.githubusercontent.com/8317741/106864962-d3eec680-66ca-11eb-8d64-4a1e0c3d80f5.png)

I can add error-handling. I imagine the api provides some info if the user is prem or not. So could either check that before making the request. Or handle the error after the request. I suggest the latter (handling the error). Easier to get started with and probably good to get add some error-handling in the services anyways?
What do you think?

**Comment by mathkruger** [comment]
Yeah, that error handling was on my plans, we just need to map all the endpoints that require premium account. Maybe we can do both, prevent the actions that require premium (for free accounts) and handling the error in the services.

**Comment by semla** [comment]
Ok, sounds reasonable. Regarding the services, what do you think about catching the error in the ServiceBase. And then if it is something that should be shown to the user, rethrow, and catch that error in the calling service? Or in cases where it makes sense, retry the request.
With this error I guess there is no point in rethrowing the error, so just handle it in the base-service and return.. null or an empty?

**Comment by mathkruger** [comment]
Sounds good! Just handle it and return null, but keeping the status code, so we know what went wrong in the services.
