### ISSUE TITLE
Translate the application to Hebrew & RTL support

### ISSUE THREAD

**Issue by dvirberlo** [mathkruger/litefy#24]
hi @mathkruger 
Are you interested in adding Hebrew language to the application?

just keep in mind that Hebrew is a right aligned language.

**Comment by dvirberlo** [comment]
Addtionally, at src\assets\i18n\he.json:
MusicListTracks singular in hebrew is: "רצועה"
MusicListTracks + MusicListTracksPlural should be "רצועות"

what i am saying is that the plural end form in Hebrew replcaes the last letter of the singular form.
what sould i do?

**Comment by mathkruger** [comment]
I think we can change the way that string is formed, creating a new string in the translation file with the plural as a whole. I never worked with RTL language, so, I'm not familiar with the techniques to make it work properly. But, you're free to do it in your own way!

**Comment by dvirberlo** [comment]
Hi.
(recommend to number your comments, best for everyone)
1. I agree.
2. In general, you can so must of the work by putting `dir="trl"` at the <body> (or at the body style `direction:rtl`).
but, there are places you will want to keep LTR (for example. the buttons div of previous, play/stop and next).
3. I very familiar with HTML and Node.js but I never worked with Angular or TypeScript. so if you want me to work on it, it might take time. but it would be a solution to any right aligned language.

**Comment by dvirberlo** [comment]
4. If you are intersted in more translations, I recommend to make a `translations.md` file to explain what files should be translated and basic language style(take [opensource.guide](https://github.com/github/opensource.guide/blob/main/docs/translations.md) as example).

**Comment by dvirberlo** [comment]
Hi, @mathkruger.
As requested, the new plural system PR #26 done.
now, remains just to dive into the Angular `i18n-dir`...

**Comment by dvirberlo** [comment]
Hi, @mathkruger.
I started to work on the `RTL`.

As it is wrriten right now, there are many places that the positioning of the elements are realtive or abssulot, which means that `dir=rtl/ltr` does affect them, or affect them unprroperly.

here there are: (I will keep working and updating the list, if needed)
1. buttons of previous song, play/stop and next song
2. magnifying glass at search input
3. opening menu of "settings", "profile" and "exit".

**Comment by dvirberlo** [comment]
Hi @mathkruger .
1. I finished the assignment (#31).
1. I used CSS `inset-inline-X` which is not compatible with all browsers ( [MDN compatibility chart](https://developer.mozilla.org/en-US/docs/Web/CSS/inset-inline#browser_compatibility) ).
if you want me to use a way which is more compatible- just let me know!

**Comment by dvirberlo** [comment]
Close the issue?
