### ISSUE TITLE
User profile screen

### ISSUE THREAD

**Issue by mathkruger** [mathkruger/litefy#3]
Create a screen for user profile informations.

**Comment by mnlima** [comment]
Vou fazer essa, beleza

**Comment by ARH-MNAJS** [comment]
is this issue still open to work upon

**Comment by LisaBelgacem** [comment]
Hello @mathkruger, @tahardassi and me would like to contribute to this issue, can you give us more details about what you want to do and also if it is still open ?

**Comment by mathkruger** [comment]
Hey @LisaBelgacem! This is just a screen with the user profile information. Web already have an object with this data saved in local storage, we need to create a screen to show it. 
Yes, it's still open, although @mnlima said he would take this one. My sugestion is, create your implementation and submit your PR, if it fits with what we need, I'll merge it!

**Comment by mathkruger** [comment]
resolved with PR #21. Thanks everyone!
