### ISSUE TITLE
Add support for more languages

### ISSUE THREAD

**Issue by raymond-design** [mathkruger/litefy#42]
I think it would be a good idea to add support for other common languages by extending the existing language switching feature.

**Comment by mathkruger** [comment]
Thanks for the idea! It would be awesome, but I really need some fluent/native speakers of those languages.

**Comment by raymond-design** [comment]
I like how one of the languages (Arabic, I think?) takes into account that it's read from right to left. Do you think there is a library of some sorts that simplifies all the translation?

**Comment by Govindkm** [comment]
Hi @mathkruger,
Tried adding Hindi language support to the application.
#54

**Comment by olevol** [comment]
Hi @mathkruger ,
I've added Ukrainian language support to the app.

**Comment by ekoirsyad** [comment]
Hi @mathkruger 

I have added Indonesian Language support to Litefy, please take a look at my pr.

#77

**Comment by ZeljkoCarevic** [comment]
I'll be adding support for Croatian in a couple of days.

**Comment by felix-khlmnn** [comment]
Hello! I'm a native German speaker. 
I will look to add German in 
the next days.

**Comment by felix-khlmnn** [comment]
> Hello! I'm a native German speaker. I will look to add German in the next days.

PR is out

**Comment by FonecaBot2** [comment]
Hello @mathkruger! I added support for Guarani language :)
This is my PR https://github.com/mathkruger/litefy/pull/81

**Comment by PedroZuck** [comment]
> I think it would be a good idea to add support for other common languages by extending the existing language switching feature. So, I am a native brazilian portuguese speaker, how can I help this projects and what are the files that I should edit or create?

**Comment by sajdakabir** [comment]
Hey @mathkruger i would like to add Bengali language .

**Comment by eleonora2687** [comment]
Hi, i m a begginer on open source software so i would like to make a contribution by adding greek language to your project
Greetings from Greece

**Comment by Casagrande578** [comment]
Hello, I am form Brazil, also new to open source, I would like to add the brazilian portuguese translation

**Comment by erezcal1** [comment]
Hello there,
I'm a beginner to open source and would like to add Hebrew language if necessary, Greetings from Israel :)

**Comment by mathkruger** [comment]
> Hello there, I'm a beginner to open source and would like to add Hebrew language if necessary, Greetings from Israel :)

Hey! Thanks for your interest, but the app already supports Hebrew. Anyway, fell free to contribute with anything you want!

**Comment by sajdakabir** [comment]
@mathkruger can you please my PR #100 
Added support for the Bengali language.

**Comment by Ambareen09** [comment]
Hey, I'd like to add German language.

**Comment by felix-khlmnn** [comment]
> Hey, I'd like to add German language.

Already done in PR #80

**Comment by ChiragSharma0208** [comment]
I would like to add Hindi language support

**Comment by sumitshinde-84** [comment]
hey i have added Marathi (indian language ) support please check PR #104

**Comment by csubiii** [comment]
Hello! @mathkruger
I've added Hungarian language support to Litefy.
Can you take a look at my PR#114 ?
Thanks!

**Comment by GowriPriyankaM** [comment]
Hey, @mathkruger 
I have added Telugu (Indian language) support to Litefy. Please have a look at my PR#122
Thanks!

**Comment by Tushar12222** [comment]
Hey, @mathkruger 
I have added Kannada (an Indain language) to support Litefy.
Can you take a look at my PR #124 ?
Thanks !!
