### ISSUE TITLE
🐛 Bug: Profile picture not showing properly

### ISSUE THREAD

**Issue by David-Lazaro-Fernandez** [mathkruger/litefy#44]
### Subject of the issue 📝
**Hi there 👋**
Hope everyone is having an amazing day 🌞
This is the first time im using **Litefy 💚**

After I have installed everything and loged in I saw that the profile picture of my user account wasn't showing properly 🤔

###  Environment 💻
Angular CLI: 10.2.1
Node: 12.18.1
OS: win32 x64
Crhome:  94.0.4606.71
Angular: 10.2.4

### Screenshot 📸
![image](https://user-images.githubusercontent.com/57787993/136100920-e6e9a86e-3904-475c-969f-ddf8ef4f72eb.png)

**Comment by mathkruger** [comment]
Thank you very much for opening this issue! I'll be working on it!

**Comment by mathkruger** [comment]
Solved with PR #47
