### ISSUE TITLE
Enhancement: The Settings drop-down menu should disappear when user clicks away

### ISSUE THREAD

**Issue by raymond-design** [mathkruger/litefy#45]
Currently, the drop-down menu (to see the profile and settings) stays dropped down after it is trigger. The drop-down menu feature on Spotify (and Github too) disappears when the user clicks elsewhere, so that the menu doesn't partially block the screen. I think this would sense too, since the language switching feature (which is beside it) also disappears when the user triggers something else.

**Comment by mathkruger** [comment]
Solved by the PR #49
