### ISSUE TITLE
Feature: Add country flags for the languages

### ISSUE THREAD

**Issue by mathkruger** [mathkruger/litefy#53]
Would be nice to have little icons with a flag representing the language. Maybe using the most relevant country that speaks that language. I don't know if this would bother someone, but I'll try to do my best lol

**Comment by sinha-toyeesh** [comment]
Hello ! I would like to work on this issue, could you assign this to me ?

**Comment by mathkruger** [comment]
@sinha-toyeesh Hey! I'm sorry but I'm already working on it :( but, fell free to take another issue to work on!

**Comment by mathkruger** [comment]
Feature added with PR #55
