### ISSUE TITLE
issue reagrding default language

### ISSUE THREAD

**Issue by DevIos01** [mathkruger/litefy#59]
hey @mathkruger 

it seems like u did fixed on #55 ([commit](https://github.com/mathkruger/litefy/pull/55/commits/1736b05367a09a57ef2d225fcd8d880def210f21))
```ts
this.translate.setDefaultLang(languages.includes(navigator.language) ? navigator.language : "en");
```
1. it still loads a "ukraine" language on the first start rather than "EN" a global language even tho in language picker it is set to English.
[showing the problem](https://imgur.com/InkgGVh)

NOTE: it seems to be like if you remove the ua.json the default goes back to en 

just wanted to create the issue to make sure it is not intended before I make a pull request

also regarding the push the update of .gitignore to add these two files because it wasn't before :
package-lock.json
yarn.lock

**Comment by mathkruger** [comment]
Thanks very much for pointing it out and correcting this bug!
