### ISSUE TITLE
Add support for navigating with keyboard

### ISSUE THREAD

**Issue by mathkruger** [mathkruger/litefy#6]
This feature is important for integration with KaiOS, a platform that does not have a Spotify client.

**Comment by DevIos01** [comment]
hey @mathkruger 

can you elaborate on this, do you mean to make the website combability with keyboard shortcuts?
example:  [image reference ](https://i.redd.it/wsa8t7q2aya61.png)

if yes is it something u currently working or do you want some hand of help :)

**Comment by mathkruger** [comment]
Hey!
Well, I was planning this to allow the users to navigate through the app with the arrow keys (like you would do with a tv remote). It's not a very important feature, but it's a cool addition I would like to make.

**Comment by DevIos01** [comment]
You mean something like a currently pressing a tab button would do in pc? Or do you mean like the shortcut keys

**Comment by mathkruger** [comment]
Well, after thinking more about it, I don't think this is valuable enough for this project. So, I'm closing it.
