### ISSUE TITLE
UI/UX improvements

### ISSUE THREAD

**Issue by ABSanthosh** [mathkruger/litefy#66]
Hey!
Great project you have there but the UI can have some love as well. 

Do you mind If i do some improvements like consistent, responsive UI and UI elements?

**Comment by mathkruger** [comment]
Hey, thanks for your interest on this little project.
Sure, you're more than welcome to do it!

**Comment by ABSanthosh** [comment]
> @ABSanthosh may I work on this with you?
> I was thinking the same thing too

Hey! If @mathkruger is fine with that, I am too. Let’s connect after May 12 and discuss about the designs.

**Comment by fortune710** [comment]
@ABSanthosh Alright then, no problem!

**Comment by fortune710** [comment]
@ABSanthosh What platform can we connect on?

**Comment by ABSanthosh** [comment]
@fortune710 If discord is fine for you, heres my id: Santhosh#1357

**Comment by fortune710** [comment]
@ABSanthosh Alright no problem
