### ISSUE TITLE
Create tests cases for every component

### ISSUE THREAD

**Issue by mathkruger** [mathkruger/litefy#9]
yes. we need this.

**Comment by ARH-MNAJS** [comment]
Can you please elaborate on your requirements

**Comment by mathkruger** [comment]
We need to create test cases for every component and service in the application. We are using karma + jasmine (standart testing stack for angular) in the project. I already created some tests, but all the services need at least one test case yet.

**Comment by vandana1499** [comment]
I would like to work on it. I will  add test cases to level so that its good to go.

**Comment by raymond-design** [comment]
Hello Matheus, I can help write some tests. However, the newest build is broken on my end.

**Comment by Hdanzo** [comment]
Hey, I'd like to help writing some service tests.

**Comment by mathkruger** [comment]
@Hdanzo Hey! feel free to do it, I'm using Jasmine for tests so it should not be a problem. Thanks!

**Comment by matiasosorio1999** [comment]
Hello! I created some tests for the Settings service.
It's in this PR #84

**Comment by surajy93** [comment]
Hi @mathkruger i can write the test case, could you please guide to setup and some docs related to feature and all.

**Comment by avinashji1302** [comment]
Hey @mathkruger  Could you please me this ?

**Comment by mathkruger** [comment]
We need to update the angular version o the app first. I'm closing this issue and I'll open another one in the future.
